<center><h1>
    
    𝔾𝕖𝕥𝕥𝕚𝕟𝕘 𝕊𝕥𝕒𝕣𝕥𝕖𝕕 𝕨𝕚𝕥𝕙 
    𝕥𝕙𝕖 𝕄𝕠𝕕𝕖𝕝 𝔸𝕣𝕔𝕙𝕚𝕥𝕖𝕔𝕥𝕦𝕣𝕖 
    𝕠𝕗 𝕥𝕙𝕖 𝕋𝕣𝕒𝕟𝕤𝕗𝕠𝕣𝕞𝕖𝕣
</h1></center>    
    
[**Codes**](https://github.com/PacktPublishing/Transformers-for-Natural-Language-Processing)

## Overview
In December 2017, the seminal Vaswani et al. Attention Is All You Need article, written 
by Google Brain members and Google Research, was published. The Transformer 
was born. The Transformer outperformed the existing state-of-the-art NLP models. 
The Transformer trained faster than previous architectures and obtained higher 
evaluation results. Transformers have become a key component of NLP.

Before this innovation, there are lot's of innovation from early's ninties, There are lot's of problem with the old network like, long short term memory. To overcome this the **Transformer came**. The main important point is **This is parallel computing** compare to old RNN, CNN, BLSTM, this is a parallel computing. 

Here there is no RNN, CNN, LSTM, BRNN, BLSTM, here the new concept let's break it ...

<center><img src="https://quantdare.com/wp-content/uploads/2021/11/transformer_arch.png" width="400" height="200"/></center>

There is a 6-layer encoder stack 
on the left and a 6-layer decoder stack on the right. On the left, the inputs enter the encoder side of the Transformer through an attention 
sub-layer and FeedForward Network (FFN) sub-layer. On the right, the target 
outputs go into the decoder side of the Transformer through two attention sub-layers 
and an FFN sub-layer.

The attention mechanism 
is a **"word-to-word"** operation. The attention mechanism will find how **each word 
is related to all other words in a sequence**, including the word being analyzed itself..

Let's see some example: 

```
Example word: 
The cat sat on the mat.
```

<img src="images/att.png" width="600"/>


Attention will run dot products between word vectors and determine the strongest 
relationships of a word among all the other words, including itself ("cat" and "cat"):, 

NOte: **Here we are not running single attention system, we are parallely running 8 attention systems**. 

## The Encoder Stack


The layers in the tranformers are **stack of layers**. Let's see the encoder architecture now! 

<center><img src="https://www.researchgate.net/publication/334288604/figure/fig1/AS:778232232148992@1562556431066/The-Transformer-encoder-structure.ppm" width="300"/></center>

Each layer contains two main sub-layers: a **multi-headed 
attention mechanism** and a **fully connected position-wise feedforward network.**

These connections transport the unprocessed input **x** of a **sublayer** to a **layer normalization** function. This way, we are certain that key information 
such as **positional encoding is not lost on the way**. The normalized output of each 
layer is thus:

```
LayerNormalization (x + Sublayer(x))
```


The designers of the Transformer introduced a very efficient constraint. The output 
of every sub-layer of the model has a constant dimension, including the embedding 
layer and the residual connections. This dimension is dmodel and can be set to another 
value depending on your goals. In the original Transformer architecture, d(model) =512.
d(model) has a powerful consequence. 

Practically all the key operations are dot products. 
The dimensions remain stable, which reduces the number of operations to calculate, 
reduces machine consumption, and makes it easier to trace the information as it 
flows through the model

Let's go from very scratch

### The inputs Embedding 

The input embedding sub-layer converts the input tokens to vectors of dimension 
d = 512 using learned embeddings in the original Transformer model. The 
structure of the input embedding is classical:

<center><img src="images/input.png" width="500"/></center>

The embedding sub-layer works like other standard transduction models. A 
tokenizer will transform a sentence into tokens. Each tokenizer has its methods, 
but the results are similar. For example, a tokenizer applied to the sequence 
```"the 
Transformer is an innovative NLP model!" 
```
will produce the following tokens in 
one type of model

```Python 
['the', 'transform', 'er', 'is', 'a', 'revolutionary', 'n', 'l', 'p', 'model', '!']
```
You will notice that this tokenizer normalized the string to lower case and truncated 
it into subparts. A tokenizer will generally provide an integer representation that will 
be used for the embedding process. For example:

```Python 
Text = "The cat slept on the couch.It was too tired to get up."
tokenized text= [1996, 4937, 7771, 2006, 1996, 6411, 1012, 2009, 2001, 2205, 5458, 2000, 2131, 2039, 1012]

```

There is no other way to be tokenize this sentence, so it need to be embedded, The Transformer contains a learned embedding sub-layer. The learned embedding sublayer should be given by us (I mean we need to embedding the sentence to same size), in the transformer they used `512` dimensions, you can use whatever you want.  You can use `word2vec` or `Glove` whatever you want, but this needs to be in the same dimensions. 

However, a big chunk of information is missing because no additional vector or information indicates a word's position in a sequence. (I mean which word came whic area) EX: 

```
MY name is aravind
```

We need to specify the position of the word `my` as `1`, `name` as `2` like that. If we do this we don't loss the `context` of the sentence. 

### Positional Encoding: 

<center><img src="images/pos.png" width="500"/></center>

We will pass **high dimension** vector to the **input embedding**, the vector space should be very high. So, it's tough to find which word is starting of the sentence, which word is middle of the sentence like that, instead of having additional vectors to describe the position of the vectors. The idea is to add **`positional encoding`** value to the input embedding. 


If we go back to the sentence we used in the word embedding sub-layer, we can see 
that black and brown may be similar, but they are far apart:

Example: 
**`The black cat sat on the couch and the brown dog slept on the rug.`**

The word black is in position 2, pos=2, and the word brown is in position 10, pos=10. 

Our problem is to find a way to add a value to the word embedding of each word 
so that it has that information. However, we need to add a value to the dmodel = 512 
dimensions! For each word embedding vector, we need to find a way to provide 
information to i in the range(0,512) dimensions of the word embedding vector of 
black and brown. 

There are many ways to do this, one of the clever way is that unit sphere to represent positional encoding with sine and cosine values. 

<center><img src="images/fom.png" width="500"/></center>

If we start at the beginning of the word embedding vector, we will begin with a 
constant (512), i=0, and end with i=511. This means that the sine function will be 
applied to the even numbers and the cosine function to the odd numbers. Some 
implementations do it differently. In that case, the domain of the sine function can be 
𝑖𝑖 ∈ [0,255] and the domain of the cosine function can be 𝑖𝑖 ∈ [256,512]. This will produce 
similar results.


```Python
# Positional encoding: 

import math 
def positional_encoding(pos, pe): 
    
    for i in range(0, 512, 12): 
        pe[0][i] = math.sin(pos / (10000* ((2 * i) / d_model)) ) 
        pe[0][i+1] = math.cos(pos / (10000 ** ((2 * i)/d_model)) ) 
    return pe 
```

If we go back to the sentence we are parsing in this section, we can see that black is 
in position pos=2 and brown is in position pos=10:

`
The black cat sat on the couch and the brown dog slept on the rug.`

If we apply the sine and cosine functions literally for pos=2, we obtain a size=512
positional encoding vector:

<center><img src="images/pos_vec.png" width="500"/></center>

The cosine similarity function used for word embedding comes in handy for having 
a better visualization of the proximity of the positions:

`cosine_similarity(pos(2), pos(10)= [[0.8600013]]` # pos 2 -> black, pos 3 -> brown 

The similarity between the position of the words black and brown and the lexical 
field (groups of words that go together) similarity is different:

`cosine_similarity(black, brown)= [[0.9998901]]`

The encoding of the position shows a lower similarity value than the word 
embedding similarity, In simple words, the cosine similarity of the normal word `black and brown` is high, whereas the positonal encoding of the same word is less, this is due to positional encoding operations. 

To solve this, we will use this simple formula: 

<center><img src="images/podu.png" width="500"/></center>

**`pc(black)=y1+pe(2)`**

The solution is straightforward. However, if we apply it as shown, we might lose 
the information of the word embedding, which will be minimized by the positional 
encoding vector.

There are many possibilities to increase the value of y1 to make sure that the 
information of the word embedding layer can be used efficiently in the subsequent 
layers.

One of the many possibilities is to add an arbitrary value to y1, the word embedding 
of black:

**`y1*math.sqrt(dmodel)`** 

If we apply this to the vectors, we will get the cosine similarity like

<center><img src="images/final.png" width="800"/></center>

**`This output will go the multi-head attention sub-layer`**

### SubLayer1 MultiHeadAttention

The multi-head attention sub-layer contains **eight heads** and is followed by post **layer normalization**, which will add residual connections to the output of the sublayer and normalize it:

<center><img src="images/sub.png" width="500"/></center>

The input of the multi-attention sub-layer of the first layer of the encoder stack is a 
vector that contains the embedding and the positional encoding of each word.

vector = **`pe(xn)=[d1 =9.09297407e-01, d2=9.09297407e-01,.., d512 = 1.00000000e+00]`**

`Sentence = The cat sat on the rug and it was dry cleaned`

The model will train to find out if "it" is related to "cat" or "rug." We could run a 
huge calculation by training the model using the dmodel = 512 dimensions as they are 
now.

We are running 8 heads, if we run all the sentence in a one head, it will take time, so we are going to divide by 8. why eight, if you want to run parallely (we have 8 heads) 512//3 = 64, so we can give 64 vector to each head for parallel computing. 

<center><img src="images/8.png" width="700"/></center>

The each head determies the `it` refers to cat or rug. The output of this is a matrix z = 

**`Z = (z0
, z1
, z2
, z3
, z4
, z5
, z6
, z7
,)
`**


NOw the **Z** is the sequence of output, we need a single output, so we will concatenate this 

**`MultiHead(output) = Concat(z0, z1, z2, z3, z4, z5, z6, z7,) = x, dmodel`**

Let's see what's inside each head. In each head(vector) has three representation: 

* Querey Vector
* Key Vector 
* Value Vector 
---
* A query vector (Q) that has a dimension of dq = 64, which is activated and  trained when a word vector xn  seeks all of the key-value pairs of the other  word vectors, including itself in self-attention
* A key vector (K) that has a dimension of dk = 64, which will be trained to provide an attention value
* A value vector (V) that has a dimension of dv= 64, which will be trained to  provide another attention value

Attention is defined as "Scaled Dot-Product Attention," which is represented in the 
following equation in which we plug Q, K, and V:

<center><img src="images/attention.png" width="700"/></center>

The vectors all have the same dimension making it relatively simple to use a scaled 
dot product to obtain the attention values for each head and then concatenate the 
output Z of the 8 heads.

To obtain Q, K, and V, we must train the model with their respective weight matrices 
Qw, Kw and Vw, which have dk
 = 64 columns and dmodel = 512 rows. For example, Q is 
obtained by a dot-product between x and Qw. Q will have a dimension of dk
 = 64.
 
This things done internally in the hugging face transformers, Trax and more.. Let's see inside what happening in 10 steps: 

#### Step1: 

The input of the attention mechanism we are building is scaled down to dmodel = 4 
instead of dmodel = 512. This brings the dimensions of the vector of an input x down to 
dmodel = 4, which is easier to visualize. 

x contains 3 inputs with 4 dimensions each instead of 512:

ok fine, See the code [**here**](https://github.com/PacktPublishing/Transformers-for-Natural-Language-Processing/blob/main/Chapter01/Multi_Head_Attention_Sub_Layer.ipynb) from now 


In [3]:
import numpy as np 
from scipy.special import softmax
# step 1: 
''' Three inputs with the dimension of 4 '''

x = np.array([ [1.0, 0.0, 1.0, 0.0],  # input 1 
               [0.0, 2.0, 0.0, 2.0],  # input 2
               [1.0, 1.0, 1.0, 1.0]   # input 3 (consider this is the id from the respective word of vocabulary 
]) 

print(x)

[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


**`Visually`**
<center><img src="images/step1.png" width="500"/></center>

#### Step2: (Initializing the weights) 

Each input has **3 weights**. 
* Qw to train the queries. 
* Kw to train the keys. 
* Vw to train the values. 

IN the transformer paper, we have 64 dimension weights for 512 dimension. similarly we are going to have 3 dimesnsion of the vector. Then we can perform the dot product between them. 

In [12]:
# step2: (weight initialization) 

w_query =np.array([ [1, 0, 1],   # random initializaiton
                    [1, 0, 0],
                    [0, 0, 1],
                    [0, 1, 1] ])  # dimension is 4 X 3 because the input dimesion is 3 X 4 

w_key =np.array([ [0, 0, 1],
                  [1, 1, 0],
                  [0, 1, 0],
                  [1, 1, 0] ])

w_value = np.array([ [0, 2, 0],
                     [0, 3, 0],
                     [1, 0, 3],
                     [1, 1, 0] ])

<center><img src="images/step2.png" width="500"/></center>

#### Step3 (Matric Multi to Obtain Q,K,V): 

We will now multiply the input vectors by the weight matrices to obtain a query, 
key, and value vector for each input.

In this model, we will assume that there is one w_query, w_key, and w_value weight 
matrix for all inputs. Other approaches are possible. In transformers paper, we will do like 8 times. 

In [16]:
# step3 (matrix multi to obtain Q, K, V)

Q = np.matmul(x, w_query)  # input x multiply with weight matrix q 
K = np.matmul(x, w_key) 
V = np.matmul(x, w_value) 

print(Q)

[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]


**`Visually`**
<center><img src="images/step3.png" width="500"/></center>

#### Step4 (Scaled Attention Scores): 

Now, we are going to do the attention formula, we discussed earlier: 
<center><img src="images/attention.png" width="300"/></center>

Here in thi step we will focus on Q and K 

For this model, we will round √𝑑𝑘 = √3 = 1.75 to 1 and plug the values into the Q
and K part of the equation

In [19]:
# step4 (Q and K) implementation 

k_d = 1   # square root of 3 is 1.75 to 1

attention_scores = ( Q @ K.transpose() )/ k_d 

attention_scores

array([[ 2.,  4.,  4.],
       [ 4., 16., 12.],
       [ 4., 12., 10.]])

**`Visually`**

<center><img src="images/step4.png" width="500"/></center>

#### Step5 (Scaled softmax of attention output)

We now apply a softmax function to each intermediate attention score. Instead of 
doing a matrix multiplication, let's zoom down to each individual vector:

In [37]:
# step5 Scaling the attention outputs using softmax 

attention_scores[0] = softmax(attention_scores[0])  # taking first word and calculating attention 
attention_scores[1] = softmax(attention_scores[1]) 
attention_scores[2] = softmax(attention_scores[2])  # taking third word and calculating attention score... 

print(attention_scores)

[[0.25010005 0.37494998 0.37494998]
 [0.2133134  0.56950313 0.21718348]
 [0.22037557 0.53143172 0.24819272]]


**`Visually`**

<center><img src="images/step5.png" width="500"/></center>

#### Step6 (The final calculation of the attention formula) 

we have missed the v value there, let's plug in here.. 

To obtain Attention (Q,K,V) for x1
, we multiply the intermediate attention score by the 
3 value vectors one by one to zoom down into the inner workings of the equation:

In [38]:
# Step6 finising the function:

attention1 = attention_scores[0].reshape(-1,1) 
attention1 = attention_scores[0][0]*V[0]   # multiplying the input vector for 1st word [1,2,3] with v:: [1].[v[1]] [2].[v[2]] [3].[v[3]]

attention2 = attention_scores[0][1]*V[1]

attention3 = attention_scores[0][2]*V[2]

print(attention1)
print(attention2)
print(attention3)

[0.25010005 0.5002001  0.75030014]
[0.74989995 2.99959981 0.        ]
[0.74989995 2.24969986 1.12484993]


In [26]:
attention_scores[0][2]

0.4683105308334813

In [27]:
V[2]

array([2., 6., 3.])

**`Visually`**

<center><img src="images/step6.png" width="500"/></center>

#### Step7 (summing all) 

The 3 attention values of input #1 obtained will now be summed to obtain the first 
line of the output matrix:

In [30]:
# step7 summing all the first input
attention_input1 = attention1 + attention2 + attention3

print(attention_input1)

[1.93662106 6.68310531 1.59506841]


**`Visually`**

<center><img src="images/step7.png" width="500"/></center>

This is how, we need to calculate the attention score for each input, let's do this for all the inputs: 

#### Step8 (Step1 to 7 for all the inputs): 

The Transformer can now produce the attention values of input #2 and input #3 
using the same method described from Step 1 to Step 7 for one attention head.

We have seen the attention representation process in detail with a small model. 
Let's go directly to the result and assume we have generated the 3 attention 
representations with a dimension of dmodel = 64:

In [32]:
print("Step 8: Step 1 to 7 for inputs 1 to 3")

#We assume we have 3 results with learned weights (they were not trained in this example)
#We assume we are implementing the original Transformer paper. We will have 3 results of 64 dimensions each

attention_head1=np.random.random((3, 64))
print(attention_head1)   # original output of transformer paper like.. 

Step 8: Step 1 to 7 for inputs 1 to 3
[[0.10280484 0.39598973 0.45517602 0.58647984 0.58828552 0.92122988
  0.68654625 0.80763479 0.20589559 0.72121693 0.29703272 0.17667301
  0.27364887 0.17253768 0.90346001 0.90633138 0.7933515  0.51964885
  0.80541971 0.50531064 0.25783709 0.82806367 0.96314343 0.4034734
  0.79432498 0.46931542 0.19238388 0.83910951 0.04350163 0.94790374
  0.20440588 0.30288193 0.40085491 0.55028486 0.30983402 0.31681075
  0.50154442 0.00679641 0.60881248 0.10793141 0.66959068 0.53781646
  0.52632209 0.56625682 0.60856186 0.70206512 0.6267506  0.55595726
  0.50485428 0.08930771 0.9205643  0.04438278 0.67530187 0.81699594
  0.92107407 0.17636544 0.22964583 0.35607933 0.50555196 0.8029805
  0.92139223 0.22856835 0.046276   0.99414017]
 [0.21641989 0.8765781  0.77964355 0.60833895 0.99334575 0.53972279
  0.05616948 0.67679237 0.86523839 0.79496068 0.59690904 0.33907428
  0.11532851 0.04131901 0.67542439 0.05019122 0.0950849  0.56793785
  0.02515496 0.03564373 0.4734562

#### Step9 (The output of the heads of attention sub layer): 

We assume that we have trained the 8 heads of the attention sub-layer. The 
transformer now has 3 output vectors (of the 3 input vectors that are words or word 
pieces) of dmodel = 64 dimensions each:

In [33]:
# step 9

z0h1=np.random.random((3, 64))
z1h2=np.random.random((3, 64))
z2h3=np.random.random((3, 64))
z3h4=np.random.random((3, 64))
z4h5=np.random.random((3, 64))
z5h6=np.random.random((3, 64))
z6h7=np.random.random((3, 64))
z7h8=np.random.random((3, 64))

print(z0h1.shape)  # 3 input with 64 dimension (with all 8 heads) *understand? 

(3, 64)


#### Step 10: Concatenation of the output of the heads

The Transformer concatenates the 8 elements of Z:

**`
MultiHead(output) = Concat(z0
, z1
, z2
, z3
, z4
, z5
, z6
, z7
,)W0
 = x, dmodel
 `**
 
Note that Z is multiplied by W0
, which is a weight matrix that is trained as well. 
In this model, we will assume W0
 is trained and integrated into the concatenation 
function.

In [34]:
# step 10:  Concatenate all the heads we found: 

output_attention=np.hstack((z0h1,z1h2,z2h3,z3h4,z4h5,z5h6,z6h7,z7h8))
print(output_attention)

[[0.0324842  0.54600819 0.93681112 ... 0.18769341 0.79759062 0.95800028]
 [0.84281932 0.66724598 0.07297926 ... 0.55198509 0.79932052 0.00509219]
 [0.15329525 0.54213658 0.48375129 ... 0.76061418 0.06414124 0.39099882]]


In [36]:
output_attention.shape   # inputs with 512 dimension and also attention outputs. 

(3, 512)

**`Visually`**

<center><img src="images/step10.png" width="500"/></center>
<center><img src="images/step7.png" width="500"/></center>

## Layer Normalization

The output from the multi head attention layer will flow to the **post layer normalization** and some of the positional encoded input also come directly to the layer normailzation. 

<center><img src="images/ps.png" width="600"/></center>


It contain two process **add function** and **layer normalization process**. The add 
function processes the residual connections that come from the input of the sublayer. The goal of the residual connections is to make sure critical information is not 
lost. The Post-LN or layer normalization can thus be described as follows: 

**`LayerNorm = LayerNorm(x+Sublayer(x))`**

Sublayer(x) is the sub-layer itself(input of the PLN). x is the information available at the input step of Sublayer(x).The input of LayerNorm is a vector v resulting from x + Sublayer(x). dmodel = 512 for 
every input and output of the Transformer, which standardizes all the processes.

Many layer normalization methods exist, and variations exist from one model to 
another. The basic concept for v= x + Sublayer(x) can be defined by LayerNorm(v)


**`Visually`**

<center><img src="images/layernorm.png" width="500"/></center>

**Why Layer Normalization and what are all the uses?** 

Layer normalization (LayerNorm) is a technique to normalize the distributions of intermediate layers. It enables smoother gradients, faster training, and better generalization accuracy. 

Still doubt refer this [**research paper**](https://proceedings.neurips.cc/paper/2019/file/2f4fe03d77724a7217006e5d16728874-Paper.pdf)

## SubLayer2 FeedForward Neural Network

The output of the LN is input to the FFN. 

<center><img src="images/ffn.png" width="500"/></center>

It's just a normal neural network, it's fully connected FFN. This neural network is working on **Position wise**. 

**FFN containes two layers and apply the ReLU activation function**

simple neural network 

**`FFN(x) = max(0, xW1 + b1 )W2 =b2`**

The output of the FFN goes to the Post-LN, as described in the previous section. 
Then the output is sent to the next layer of the encoder stack and the multi-head 
attention layer of the decoder stack

**`IGnore feature knowledge`** just for illustraion. 

<center><img src="https://miro.medium.com/max/1304/0*esJuLjMbfGOhVnoJ.png" width="300"/></center>

## The Decoder
 
It's same like encoder, it also as a stack of layers. Let's see that 

<center><img src="images/decoder.png" width="300"/></center>

The structure of the decoder layer remains the same as the encoder for all the N=6
layers of the Transformer model. Each layer contains three sub-layers: a multi headed masked attention mechanism, a multi-headed attention mechanism, and a 
fully connected position-wise feedforward network.

### Multi head masked attention: 

The decoder has a third main sub-layer, which is the masked multi-head attention 
mechanism. In this sub-layer output, at a given position, the following words are 
masked so that the Transformer bases its assumptions on its inferences without 
seeing the rest of the sequence. That way, in this model, it cannot see future parts of 
the sequence. 

We need a method to prevent computing attention scores for future words. This method is called masking. To prevent the decoder from looking at future tokens, you apply a look ahead mask. The mask is added before calculating the softmax, and after scaling the scores. Let’s take a look at how this works.

The mask is a matrix that’s the same size as the attention scores filled with values of 0’s and negative infinities. When you add the mask to the scaled attention scores, you get a matrix of the scores, with the top right triangle filled with negativity infinities.


<center><img src="https://miro.medium.com/max/1400/0*QYFua-iIKp5jZLNT.png" width="500"/></center>

In simple words, we mask future words, the encoder will predict (so it will learn the pattern of the data)

The reason for the mask is because once you take the softmax of the masked scores, the negative infinities get zeroed out, leaving zero attention scores for future tokens

### Output and Positional Encoding: 

The structure of the sub-layers of the decoder is mostly the same as the sub-layers 
of the encoder. The output embedding layer and position encoding function are the 
same as in the encoder stack.

However, the masked multi-head attention sub-layer 1 only lets attention apply to 
the positions up to and including the current position. The future words are hidden 
from the Transformer, and this forces it to learn how to predict.


#### attention 

The multi-head attention sub-layer 2 draws information from the encoder by taking 
encoder (K, V) into account during the dot-product attention operations. This sublayer also draws information from the masked multi-head attention sub-layer 1 
(masked attention) by also taking sub-layer 1(Q) into account during the dot-product 
attention operations. The decoder thus uses the trained information of the encoder. 
We can define the input of the self-attention multi-head sub-layer of a decoder as:


Input_Attention=(Output_decoder_sub_layer-1(Q), Output_encoder_layer(K,V))

### The FFN sub-layer, the Post-LN, and the linear layer

Same as the encoder stack of layers. 
The Transformer produces an output sequence of only one element at a time:

**`Output sequence= (y1, y2, … yn)`**

The linear layer produces an output sequence with a linear function that varies per 
model but relies on the standard method:

**`y = w*x + b`**

x and b are learned parameters.

The linear layer will thus produce the next probable elements of a sequence that a 
softmax function will convert into a probable element